name: CD

on: push

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@latest

      - uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@latest
        with:
          file: ./Dockerfile
          # build-args: |
          #   APP_VERSION=${{ github.event.release.tag_name }}
          push: true
          # bragovo/golovina-api:${{ github.event.release.tag_name }}
          tags: |
            bragovo/flux-app:latest
