name: CI

on: push

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: yarn --frozen-lockfile

      - name: Format
        run: yarn biome ci .

